import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="min-h-screen bg-indigo-500 py-12 px-4 sm:px-6 lg:px-8"
        style={{
          backgroundImage: "url('/background.jpg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
        }}>
       
       <Toaster position="top-right" reverseOrder={false} />
        <main>
        {children}
        </main>
        
      </body>
    </html>
  );
}
